### ISSUE TITLE
demo link not working

### ISSUE THREAD

**Issue by dev704** [navratil/apex-qr-plugin#3]
demo link to: https://apex.oracle.com/pls/apex/f?p=QRDEMO
is returning:
The application alias "QRDEMO" can not be converted to a unique application ID

**Comment by jeffreykemp** [comment]
This will happen if someone else installs another application (e.g. the same application) in their own workspace.

The way to fix this is for the author to add **&c=_WORKSPACE_** to the end of the URL (with the name of their workspace, of course). I don't know what navratil's workspace is though.

In the meantime, I've installed it in my workspace so you can use this link in the meantime:

https://apex.oracle.com/pls/apex/f?p=QRDEMO&c=JK64

**Comment by navratil** [comment]
Thanks for reporting this!

**Comment by jeffreykemp** [comment]
I suggest you don't hardcode the application ID - if you need to reinstall it in future, you may well get a different application ID (and the ID you had might be assigned to someone else's application).
